### ISSUE TITLE
bug: can't download models on v0.4.3.117

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1317]
OS: mac m1 16gb
GIF:
![Export-1704284639483](https://github.com/janhq/jan/assets/69952136/52749851-76f2-405b-97e5-a8433cd30275)

Note: v0.4.3.113 works fine. It was just the latest build.

**Comment by louis-jan** [comment]
![Screenshot 2024-01-03 at 21 11 14](https://github.com/janhq/jan/assets/133622055/b249dc7d-8dc1-4f45-b315-9823fb504c6e)

Same root cause, due to inconsistent state persistence. Fixing it now

**Comment by louis-jan** [comment]
btw @0xSage, there seems to be a console.log error. Could you please help by attaching a screenshot of the log here?

**Comment by 0xSage** [comment]
Fixed with 118

**Comment by zocoi** [comment]
hi, I'm using 0.4.3-125 and still can't download any model, there's a popup with timeout error

**Comment by zocoi** [comment]
Thanks @0xSage, the current workaround is :
- Open App Directory, open the `model.json` file
- Download the model *.gguf file manually
- Move the model file next to `model.json`
- Now it's working

**Comment by 0xSage** [comment]
> Thanks @0xSage, the current workaround is :
> 
> * Open App Directory, open the `model.json` file
> * Download the model *.gguf file manually
> * Move the model file next to `model.json`
> * Now it's working

Wow thanks for sharing how you trouble shooted it! Dang it should work though. 

If it happens again, can you: 
1. Download nightly 126+
2. Restart the app
3. If issue persists, give me your os/device info so we can QA this!
