### ISSUE TITLE
bug: model downloads broken on nightly

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1980]
Regression on nightly
Alerted by user. I was able to verify.

To repro: 
1. Get on 0.4.6-264
2. Go to hub
3. Click download (any model)

<img width="571" alt="image" src="https://github.com/janhq/jan/assets/69952136/26e448b3-84ad-467a-9fec-f53362ddfbb4">

**Comment by 0xSage** [comment]
Note to self: I gotta stop telling users to get on nightly/experimental...

**Comment by Van-QA** [comment]
Tested on Windows and MacOS, the issue is happening on Windows, 
- Downloading only one model, but the popup is showing 2 downloading models
<img width="1053" alt="image" src="https://github.com/janhq/jan/assets/64197333/148aef8e-5545-4e58-a80f-c976ac3ad20b">

<img width="966" alt="image" src="https://github.com/janhq/jan/assets/64197333/e0c32dd8-179b-4113-9a27-38123ca28a72">
- The first progress bar is never complete, attempting to cancel it shows the error mentioned in the ticket: 
<img width="1154" alt="image" src="https://github.com/janhq/jan/assets/64197333/bf63c0b2-be08-4663-80e7-3c1602f1834e">
- Restarted the app after the second progress bar completed, the UI shows the model is available for usage, but throw something amiss.
<img width="854" alt="image" src="https://github.com/janhq/jan/assets/64197333/7f1f1a69-48e3-4f24-9d7f-d42a83dd9ec4">
No app.log recorded

**Comment by louis-jan** [comment]
Fixed in Nightly Build #265

**Comment by urmauur** [comment]
@Van-QA @louis-jan @0xSage tested on latest Nightly Build 265, works well on windows

![Screenshot 2024-02-10 061952](https://github.com/janhq/jan/assets/10354610/60148b4f-2316-484f-a341-bb5ca8df130b)
![Screenshot 2024-02-10 062001](https://github.com/janhq/jan/assets/10354610/3ff6d055-eab0-45ad-968e-ec390f3d234f)

**Comment by 0xgokuz** [comment]
I just tested this on `dev`, seems still broken?

<img width="947" alt="Screenshot 2024-02-11 at 07 08 27" src="https://github.com/janhq/jan/assets/155065525/facb521c-0db1-4f36-ba73-965e00fb8072">

I'm on _Mac OS Sonoma 14.2.1 (23C71)_

**Comment by louis-jan** [comment]
> I just tested this on `dev`, seems still broken?
> 
> 
> 
> <img width="947" alt="Screenshot 2024-02-11 at 07 08 27" src="https://github.com/janhq/jan/assets/155065525/facb521c-0db1-4f36-ba73-965e00fb8072">
> 
> 
> 
> I'm on `Mac OS Sonoma 14.2.1 (23C71)`

@0xgokuz, You have old model schema. Since you are on dev, extensions would not migrated. Please wipe Jan Data Folder and try again.

https://github.com/janhq/jan/issues/1922

**Comment by 0xgokuz** [comment]
This is resolved after I deleted `~/jan/models` folder

So `rm -rf ~/jan/models`
