### ISSUE TITLE
The \"readableStream\" argument must be an instance of ReadableStream. Received an instance of PassThrough

### ISSUE THREAD

**Issue by ilya007500** [janhq/jan#3163]
### #

- [X] I have searched the existing issues

### Current behavior

Starting from version 0.5.1 when using the Local API Server on request: http://127.0.0.1:1337/v1/chat/completions an error is displayed in the response:

    "statusCode": 409,
    "code": "ERR_INVALID_ARG_TYPE",
    "error": "Conflict",
    "message": "The \"readableStream\" argument must be an instance of ReadableStream. Received an instance of PassThrough"

### Minimum reproduction step

1. Start the server
2. Check the request in Postman

### Expected behavior

1. Start the server
2. Check the request in Postman

### Screenshots / Logs

2024-07-14T14:16:50.746Z [SERVER]::{"reqId":"req-1","res":{},"req":{"method":"POST","url":"/v1/chat/completions","hostname":"127.0.0.1:1337"},"msg":"incoming request"}

2024-07-14T14:16:50.765Z [SERVER]::{"reqId":"req-1","res":{"statusCode":409},"req":{},"msg":"The \"readableStream\" argument must be an instance of ReadableStream. Received an instance of PassThrough"}

2024-07-14T14:16:50.766Z [SERVER]::{"reqId":"req-1","res":{"statusCode":409},"req":{},"msg":"request completed","responseTime":19.25919997692108}

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.

**Comment by v0vanch0** [comment]
> We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.

This didn't help

**Comment by Van-QA** [comment]
The issue is resolved in Jan Jan v0.5.2-619
![image](https://github.com/user-attachments/assets/5ca0c2a1-0bd9-464c-b434-bfba204abd49)

**Comment by kemiz** [comment]
The issue is not resolved. It happens when you set `"stream": false`
<img width="1260" alt="Screenshot 2024-08-29 at 14 39 47" src="https://github.com/user-attachments/assets/0330a4c1-8ef7-4e10-9ad8-1555fd8e46e8">

**Comment by Van-QA** [comment]
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern

**Comment by arkeon7** [comment]
Hello, I ran in the same issue using jan v0.5.4
here the curl call :  {"model": "mistral-ins-7b-q4","messages": [{"role": "system","content": "You are an consistent assistant that like to play with jokes."},{"role": "user","content": "hello"}],"max_tokens": 2048,"stream": true,"response_format": {"type": "text"},"temperature": 0.700000}

and response
http://127.0.0.1:1337/v1/chat/completions failed! > {"statusCode":409,"code":"ERR_INVALID_ARG_TYPE","error":"Conflict","message":"The \"readableStream\" argument must be an instance of ReadableStream. Received an instance of PassThrough"}

**Comment by louis-jan** [comment]
> Hello, I ran in the same issue using jan v0.5.4 here the curl call : {"model": "mistral-ins-7b-q4","messages": [{"role": "system","content": "You are an consistent assistant that like to play with jokes."},{"role": "user","content": "hello"}],"max_tokens": 2048,"stream": true,"response_format": {"type": "text"},"temperature": 0.700000}
> 
> and response http://127.0.0.1:1337/v1/chat/completions failed! > {"statusCode":409,"code":"ERR_INVALID_ARG_TYPE","error":"Conflict","message":"The "readableStream" argument must be an instance of ReadableStream. Received an instance of PassThrough"}

The issue stems from an error response. There was a fix on the latest nightly build that outputs the error in JSON format instead of weird error response.
