### ISSUE TITLE
bug: dest.end is not a function

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#405]
**Describe the bug**

Path 1: 
- When stopping Model A, and starting Model B, I encountered the following alert modal (`dest.end` is not a function)
- The "Chat" seems to be using a different model from what is Active

<img width="270" alt="image" src="https://github.com/janhq/jan/assets/101145494/89196c59-ad72-418d-8711-972d2df55d72">

<img width="1499" alt="image" src="https://github.com/janhq/jan/assets/101145494/9528a234-ae08-4153-bace-0a242aaec58b">

Path 2: 
- Go to "My Models" and stop a running model
- See error

<img width="1799" alt="image" src="https://github.com/janhq/jan/assets/101145494/2ed551d6-786f-4f94-b22a-b2f24e1355a7">

**To Reproduce**
1. Stop a running model in "My Models"
2. Start another model in "My Models"
3. Create a New Chat

Additional path to produce the behavior: 
1. Stop a running model in "My Models"
2. See error pop up

**Desktop (please complete the following information):**
 - OS: Mac M2 Max 64GB RAM
 - Version v0.2.0
 
**Additional context**

**Comment by louis-jan** [comment]
This issue seems to have been addressed on the main branch. Will follow up til the next release

**Comment by namchuai** [comment]
@dan-jan , please retest on latest version. This issue has been addressed.

**Comment by louis-jan** [comment]
@namchuai @vuonghoainam I still see this error sometime. Let's reproduce sometime this week (we definitely have to review nitro subprocess x app)

**Comment by louis-jan** [comment]
Blocking CI, on it
