### ISSUE TITLE
bug: Can not parse the stream from OpenRouter

### ISSUE THREAD

**Issue by axetroy** [janhq/jan#4804]
### Jan version

0.5.15

### Describe the Bug

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/803385f0-b015-422d-bd3c-1e8ff1d068d2" />

### What is your OS?

- [x] MacOS
- [ ] Windows
- [ ] Linux

**Comment by david-menloai** [comment]
hi @axetroy can you please help try v0.5.16?
this issue should be resolved.
thank you

**Comment by louis-menlo** [comment]
Please reopen issue in case it still persist. Marked as addressed.
